server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

app:
  cdc:
    topic: CDC-INPUT
    initial-count: 2000
    min-events-per-second: 0
    max-events-per-second: 0

    gap:
      enabled: true
      probability: 0.0   # 10% of events are GAP

