server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    streams:
      application-id: sf-cdc-normalizer
      properties:
        # put state somewhere obvious
        state.dir: ./target/kstreams-state

app:
  topics:
    input: SF-CDC
    output: SF-CDC-OUTPUT
    recovery: SF-CDC-RECOVERY
    refreshRequest: SF-CDC-REFRESH-REQUEST

  normalizer:
    storeName: record-state-store
    maxBufferPerRecord: 500

logging:
  level:
    org.apache.kafka.streams: INFO
    org.apache.kafka.clients: INFO
    org.springframework.kafka.streams: INFO
    com.processor: DEBUG