configurationOverrides:
  listeners: PLAINTEXT://:9092
  advertised.listeners: PLAINTEXT://local-kafka.default.svc.cluster.local:9092
  listener.security.protocol.map: "PLAINTEXT:PLAINTEXT"
  sasl.enabled.mechanisms: ""
  sasl.mechanism.inter.broker.protocol: ""